### ISSUE TITLE
error 404 after install

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/yunomonitor_ynh#2]
```
VPS in a DC

# yunohost -v
yunohost: 
  repo: stable
  version: 4.0.8.2
yunohost-admin: 
  repo: stable
  version: 4.0.4
moulinette: 
  repo: stable
  version: 4.0.3
ssowat: 
  repo: stable
  version: 4.0.5
```
hello, 
i have a 404 errror just after install, 
same error 404 with a second ynh server, 

do you co,fimr the app is still working on your side ?
perhaps am i wrong when i install it, 

thx for your help
